spring:
  # Define H2 Console settings
  # http://localhost:8080/h2-console
  datasource:
    driver-class-name: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:testdb
    username: sa
    # Enable H2 Console

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    properties:
      hibernate:
        format_sql: true
        ddl-auto: update
    show-sql: false
  sql:
    init:
      platform: h2